#!/bin/bash
#
# Production Deployment Plan for Variant Pricing Fix
# 
# Since direct SQL modification caused syntax errors,
# this script creates a safer approach by:
# 1. Keeping existing API structure intact
# 2. Adding variant data via post-processing
# 3. Ensuring backward compatibility
#

echo "🚀 VARIANT PRICING FIX - PRODUCTION DEPLOYMENT PLAN"
echo "=================================================="
echo ""

echo "📋 CURRENT STATUS:"
echo "• Frontend variant processing system: ✅ Ready"
echo "• Backend API returning gadget data: ✅ Working"
echo "• Backend API missing variant data in listings: ❌ Issue"
echo ""

echo "🔧 RECOMMENDED SAFE APPROACH:"
echo ""
echo "Option 1: Post-process variant data (Immediate fix)"
echo "  - Modify gadgets_list() to fetch variants separately"
echo "  - Merge variant data with main gadget data"
echo "  - No SQL query changes, minimal risk"
echo ""
echo "Option 2: Add include_variants parameter"
echo "  - Add optional parameter to include variants in response"
echo "  - Default behavior unchanged"
echo "  - Progressive enhancement"
echo ""

echo "📋 IMPLEMENTATION STEPS:"

echo ""
echo "Step 1: Create helper function to fetch variants for multiple gadgets"
echo "// Add to index.php near other gadget functions"
echo "function get_variants_for_gadgets(\$gadgetIds) {"
echo "    \$db = DatabaseConnection::getInstance();"
echo "    \$conn = \$db->getConnection();"
echo "    if (!\$conn) return [];"
echo ""
echo "    \$placeholders = str_repeat('?,', count(\$gadgetIds) - 1) . '?';"
echo "    \$sql = \"SELECT gadget_id, id, color, storage, condition_status, price, price_gbp, stock_quantity "
echo "            FROM gadget_variants "
echo "            WHERE gadget_id IN (\$placeholders) AND is_active = 1 AND stock_quantity > 0\";"
echo ""
echo "    \$stmt = \$conn->prepare(\$sql);"
echo "    \$stmt->bind_param(str_repeat('i', count(\$gadgetIds)), ...\$gadgetIds);"
echo "    \$stmt->execute();"
echo "    \$result = \$stmt->get_result();"
echo ""
echo "    \$variants = [];"
echo "    while (\$row = \$result->fetch_assoc()) {"
echo "        \$variants[\$row['gadget_id']][] = ["
echo "            'id' => (int)\$row['id'],"
echo "            'color' => \$row['color'],"
echo "            'storage' => \$row['storage'],"
echo "            'condition_status' => \$row['condition_status'],"
echo "            'price' => (float)\$row['price'],"
echo "            'price_gbp' => \$row['price_gbp'] ? (float)\$row['price_gbp'] : null,"
echo "            'stock_quantity' => (int)\$row['stock_quantity']"
echo "        ];"
echo "    }"
echo "    \$stmt->close();"
echo "    return \$variants;"
echo "}"

echo ""
echo "Step 2: Modify gadgets_list() to use helper function"
echo "// In the data processing section (around line 260)"
echo "\$list = [];"
echo "while (\$row = \$res->fetch_assoc()) {"
echo "    \$specs = \$row['specifications'] ? json_decode(\$row['specifications'], true) : [];"
echo "    \$list[] = ["
echo "        'id' => (int)\$row['id'],"
echo "        'name' => \$row['name'],"
echo "        // ... other fields ..."
echo "        'date' => \$row['created_at'],"
echo "    ];"
echo "}"
echo ""
echo "// NEW: Add variant data to each gadget"
echo "\$gadgetIds = array_column(\$list, 'id');"
echo "if (!empty(\$gadgetIds)) {"
echo "    \$variantsMap = get_variants_for_gadgets(\$gadgetIds);"
echo "    foreach (\$list as &\$gadget) {"
echo "        \$gadgetId = \$gadget['id'];"
echo "        \$gadgetVariants = \$variantsMap[\$gadgetId] ?? [];"
echo "        "
echo "        // Calculate lowest variant prices"
echo "        \$lowestPrice = null;"
echo "        \$lowestPriceGbp = null;"
echo "        \$totalVariantStock = 0;"
echo "        "
echo "        foreach (\$gadgetVariants as \$variant) {"
echo "            if (\$lowestPrice === null || \$variant['price'] < \$lowestPrice) {"
echo "                \$lowestPrice = \$variant['price'];"
echo "            }"
echo "            if (\$variant['price_gbp'] !== null && "
echo "                (\$lowestPriceGbp === null || \$variant['price_gbp'] < \$lowestPriceGbp)) {"
echo "                \$lowestPriceGbp = \$variant['price_gbp'];"
echo "            }"
echo "            \$totalVariantStock += \$variant['stock_quantity'];"
echo "        }"
echo "        "
echo "        // Add variant-aware fields"
echo "        \$gadget['variants'] = \$gadgetVariants;"
echo "        \$gadget['has_variants'] = !empty(\$gadgetVariants);"
echo "        \$gadget['variant_count'] = count(\$gadgetVariants);"
echo "        \$gadget['total_variant_stock'] = \$totalVariantStock;"
echo "        \$gadget['lowest_variant_price'] = \$lowestPrice;"
echo "        \$gadget['lowest_variant_price_gbp'] = \$lowestPriceGbp;"
echo "        "
echo "        // Override prices with lowest variant prices if better deal"
echo "        if (\$lowestPrice !== null && \$lowestPrice < \$gadget['price']) {"
echo "            \$gadget['effective_price'] = \$lowestPrice;"
echo "        } else {"
echo "            \$gadget['effective_price'] = \$gadget['price'];"
echo "        }"
echo "        "
echo "        if (\$lowestPriceGbp !== null && \$lowestPriceGbp < (\$gadget['price_gbp'] ?? \$gadget['price']/2358)) {"
echo "            \$gadget['effective_price_gbp'] = \$lowestPriceGbp;"
echo "        } else {"
echo "            \$gadget['effective_price_gbp'] = \$gadget['price_gbp'] ?? \$gadget['price']/2358;"
echo "        }"
echo "    }"
echo "}"

echo ""
echo "📋 TESTING VERIFICATION:"
echo "After deployment, run:"
echo "curl -s \"https://sparkle-pro.co.uk/api/gadgets?limit=1\" | jq '.data[0] | {id, name, has_variants, variant_count, total_variant_stock, lowest_variant_price}'"
echo ""
echo "Expected output should show:"
echo "- has_variants: true/false"
echo "- variant_count: number of variants"
echo "- total_variant_stock: sum of variant quantities"
echo "- lowest_variant_price: minimum variant price"

echo ""
echo "📋 ROLLBACK PLAN:"
echo "If issues occur:"
echo "1. Comment out the variant processing code"
echo "2. API will return to original behavior"
echo "3. No data loss or corruption"

echo ""
echo "✅ This approach ensures:"
echo "• Zero downtime deployment"
echo "• Backward compatibility maintained"
echo "• Easy rollback if needed"
echo "• Gradual rollout capability"
echo "• Minimal risk to existing functionality"